# Generated by Django 4.1.1 on 2022-09-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_filmwork_person_alter_filmwork_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='genres',
            new_name='genre',
        ),
    ]
