version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    env_file:
      - .env

  movies-admin:
    build: movies-admin
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./movies-admin/static:/data/static:ro
    depends_on:
      - movies-admin
    ports:
      - "80:80"
